"""
Render an accreditation / licensing / certification report to PDF.

Division of labour: the agent decides *what* to recommend and supplies the
links, this module only lays it out. That keeps the recommendations tailored to
whatever the CSD commodity codes actually say, rather than to a fixed table.

Because the content is model-written, the report states plainly on every copy
that the links are AI-generated and must be verified, and carries the same
non-binding notice the rest of the onboarding advice uses.
"""

import re
import uuid
from datetime import datetime

from fpdf import FPDF

from agent.file_paths import generated_dir, public_url
from agent.generated_files import register as register_generated

BRAND = (200, 51, 31)
INK = (40, 40, 40)
MUTED = (110, 110, 110)

PRIORITY_ORDER = {"high": 0, "medium": 1, "low": 2}
PRIORITY_LABEL = {
    "high": "PRIORITY - DO THIS FIRST",
    "medium": "WORTH DOING",
    "low": "CONSIDER LATER",
}

# fpdf2's core fonts are latin-1 only. Model output routinely contains
# em-dashes, curly quotes and bullets, and passing those straight to
# pdf.cell() raises UnicodeEncodeError - i.e. the report fails at the last
# step, after the model has already done the expensive part.
_SUBSTITUTIONS = {
    "—": "-", "–": "-", "‘": "'", "’": "'",
    "“": '"', "”": '"', "•": "-", "…": "...",
    " ": " ", "→": "->", "×": "x",
}


def _latin1(text) -> str:
    """Make model-written text safe for a core-font PDF, losing as little as possible."""
    s = "" if text is None else str(text)
    for bad, good in _SUBSTITUTIONS.items():
        s = s.replace(bad, good)
    # Anything still outside latin-1 would raise on output; drop it rather than
    # fail the whole report.
    return s.encode("latin-1", "ignore").decode("latin-1")


def _clean_url(url) -> str:
    """Keep only http(s) links; anything else is dropped rather than rendered."""
    s = _latin1(url).strip()
    if not re.match(r"^https?://[^\s]+$", s):
        return ""
    return s


class _Report(FPDF):
    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 7)
        self.set_text_color(*MUTED)
        self.cell(0, 4, _latin1(
            "Non-binding guidance generated by CairoAI. Verify every requirement "
            "and link with the relevant regulatory body before acting."
        ), align="C", ln=1)
        self.cell(0, 4, f"Page {self.page_no()}", align="C")


def generate_accreditation_report(company_profile: dict, items: list,
                                  company_id: str = None) -> dict:
    """
    Build the PDF.

    `items` is the model's list. Each entry may carry:
        name      - what to get (required; entries without one are skipped)
        body      - the issuing/regulating organisation
        category  - Accreditation / Licence / Certification
        priority  - high | medium | low
        why       - why it matters for this company
        url       - where to apply or read more
    """
    if not items:
        return {"status": "error", "message": "No accreditation items supplied."}

    company_name = company_profile.get("company_name") or "YOUR COMPANY"
    industry = company_profile.get("industry") or "Not specified"
    bbbee = company_profile.get("bbbee_level")
    reg_no = company_profile.get("registration_number") or "Not on file"
    csd_no = company_profile.get("supplier_number") or "Not on file"

    # Keep only usable entries, then order by priority so the first page is the
    # part that actually matters.
    clean = [i for i in items if isinstance(i, dict) and i.get("name")]
    if not clean:
        return {"status": "error", "message": "No accreditation items had a name."}
    clean.sort(key=lambda i: PRIORITY_ORDER.get(str(i.get("priority", "medium")).lower(), 1))

    pdf = _Report()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Header band
    pdf.set_fill_color(*BRAND)
    pdf.rect(0, 0, 210, 32, "F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Arial", "B", 18)
    pdf.ln(8)
    pdf.cell(0, 10, _latin1("ACCREDITATION & LICENSING ROADMAP"), ln=1, align="C")
    pdf.set_font("Arial", "", 10)
    pdf.cell(0, 6, _latin1(company_name), ln=1, align="C")

    # Company context
    pdf.set_text_color(*INK)
    pdf.ln(14)
    pdf.set_font("Arial", "B", 10)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 8, _latin1("  COMPANY PROFILE USED FOR THIS ASSESSMENT"), ln=1, fill=True)
    pdf.ln(2)

    def row(label, value):
        # x is set explicitly on every line rather than relying on where the
        # previous cell left it: fpdf 1.7 returns x to the left margin after a
        # multi_cell, fpdf2 returns it to the cell's own left edge. Depending on
        # that difference makes each row drift further right under fpdf2 until
        # there is no width left and it raises "Not enough horizontal space".
        # requirements.txt installs fpdf2, so the deployed behaviour is the one
        # that breaks.
        pdf.set_x(pdf.l_margin)
        pdf.set_font("Arial", "B", 9)
        pdf.cell(45, 6, _latin1(f"  {label}"), border=0)
        pdf.set_font("Arial", "", 9)
        pdf.set_x(pdf.l_margin + 45)
        pdf.multi_cell(pdf.w - pdf.r_margin - pdf.l_margin - 45, 6, _latin1(value))

    row("Registration number", reg_no)
    row("CSD supplier number", csd_no)
    # bbbee_level is an int in parsed CSD fields but a string like
    # "Level 1 Contributor" in a stored profile, so only add the word when it
    # is not already there - otherwise it renders as "Level Level 1".
    if bbbee in (None, ""):
        bbbee_text = "Not on file"
    elif str(bbbee).strip().lower().startswith("level"):
        bbbee_text = str(bbbee).strip()
    else:
        bbbee_text = f"Level {bbbee}"
    row("B-BBEE level", bbbee_text)
    row("Industry / commodity", industry)
    row("Generated", datetime.now().strftime("%d %B %Y"))

    # Recommendations, grouped by priority band
    pdf.ln(6)
    current_band = None
    for item in clean:
        band = str(item.get("priority", "medium")).lower()
        if band not in PRIORITY_LABEL:
            band = "medium"
        if band != current_band:
            current_band = band
            pdf.ln(3)
            pdf.set_font("Arial", "B", 10)
            pdf.set_text_color(255, 255, 255)
            pdf.set_fill_color(*BRAND)
            pdf.cell(0, 7, _latin1(f"  {PRIORITY_LABEL[band]}"), ln=1, fill=True)
            pdf.set_text_color(*INK)
            pdf.ln(2)

        # Same reason as row(): never inherit x from the previous cell.
        body_w = pdf.w - pdf.r_margin - pdf.l_margin

        name = _latin1(item.get("name"))
        category = _latin1(item.get("category") or "")
        pdf.set_x(pdf.l_margin)
        pdf.set_font("Arial", "B", 11)
        pdf.multi_cell(body_w, 6, name + (f"  ({category})" if category else ""))

        if item.get("body"):
            pdf.set_x(pdf.l_margin)
            pdf.set_font("Arial", "I", 9)
            pdf.set_text_color(*MUTED)
            pdf.multi_cell(body_w, 5, _latin1(f"Issued by: {item['body']}"))
            pdf.set_text_color(*INK)

        if item.get("why"):
            pdf.set_x(pdf.l_margin)
            pdf.set_font("Arial", "", 9)
            pdf.multi_cell(body_w, 5, _latin1(item["why"]))

        url = _clean_url(item.get("url"))
        if url:
            pdf.set_x(pdf.l_margin)
            pdf.set_font("Arial", "U", 9)
            pdf.set_text_color(*BRAND)
            # cell() rather than multi_cell(): only cell() carries a link in this
            # fpdf version. Long URLs are truncated for display so they cannot
            # overflow the margin, while the anchor still opens the full address.
            shown = url if len(url) <= 90 else url[:87] + "..."
            pdf.cell(0, 5, shown, ln=1, link=url)
            pdf.set_text_color(*INK)

        pdf.ln(3)

    # Closing notice. This is model-written content, so say so on the document
    # itself rather than only in the chat message that delivered it.
    pdf.ln(4)
    pdf.set_font("Arial", "B", 9)
    pdf.set_fill_color(250, 235, 232)
    pdf.cell(0, 7, _latin1("  BEFORE YOU ACT ON THIS"), ln=1, fill=True)
    pdf.set_font("Arial", "", 8)
    pdf.ln(1)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(pdf.w - pdf.r_margin - pdf.l_margin, 4.5, _latin1(
        "This roadmap was generated by CairoAI's assistant from the documents in your "
        "Compliance Vault. The recommendations and the web links in it are AI-generated: "
        "treat them as a starting point for your own research, not as a verified list. "
        "Links may be out of date or point to the wrong page, and requirements differ by "
        "province, municipality and tender. Confirm each requirement directly with the "
        "issuing body before spending money or committing to a bid. This is not a "
        "compliance audit and it is not legal advice."
    ))

    filename = f"accreditation_roadmap_{uuid.uuid4().hex[:10]}.pdf"
    filepath = generated_dir() / filename
    pdf.output(str(filepath))
    register_generated(filename, company_id, "accreditation_roadmap")

    return {
        "status": "success",
        "filename": filename,
        "pdf_url": public_url(filename),
        "item_count": len(clean),
        "priorities": {
            band: sum(1 for i in clean if str(i.get("priority", "medium")).lower() == band)
            for band in ("high", "medium", "low")
        },
    }
