"""
Keeping Google Drive push channels alive.

=============================================================================
THE NUMBER THAT MATTERS: 86,400
=============================================================================
A Drive `files.watch` channel lives for at most **86,400 seconds (1 day)**, and
for **3,600 seconds (1 hour)** if you do not ask for more. It is not ~7 days.
That figure is what the original spec assumed, and building on it produces a
renewal schedule that silently lets every channel die -- the webhook simply
stops arriving, no error is raised anywhere, and the first symptom is a user
asking why their tender folder stopped syncing a fortnight ago.

There is also no way to extend a channel in place. "Renewal" is: create a
replacement, confirm it, then `channels.stop` the old one. In that order.

=============================================================================
WHY A DAILY CRON IS BROKEN BY CONSTRUCTION
=============================================================================
Take TTL = 86,400s, a cron period P, and a predicate "renew if the channel
expires within `threshold` seconds".

A channel is eligible for renewal during the window

    [expiry - min(threshold, TTL),  expiry)

whose length is L = min(threshold, TTL). Cron ticks are spaced P apart, and
the channel's creation time has arbitrary phase relative to them -- nothing
aligns a scheduler to the moment a user connected their Drive. In the worst
phase, a half-open window of length L contains exactly

    floor(L / P)

ticks. That is the number of chances the system is *guaranteed* to get. And
the first eligible tick lands anywhere in [expiry - L, expiry - L + P), so the
overlap between the replacement and the old channel is guaranteed to exceed

    L - P

and nothing more.

Now substitute a daily cron, P = 86,400, with the only threshold that makes
sense at that cadence, 24h:

    L                    = min(86,400, 86,400) = 86,400
    guaranteed attempts  = floor(86,400 / 86,400) = 1
    survivable failures  = 1 - 1 = 0
    guaranteed overlap   = 86,400 - 86,400 = 0

One attempt. Zero tolerance. If that single run is late, throttled, hits a
cold start, hits a 5xx from Drive, or lands in a deploy window, the channel is
dead and the next opportunity is 24 hours after it already expired. And the
overlap is zero, so even the successful case hands over at the exact instant
of expiry with no margin for clock skew between our scheduler and Google's
expiry clock.

There is a second, subtler failure. With threshold >= TTL the predicate
"expires within 24 hours" is **true for every channel from the moment it is
created**. It carries no information: it does not select the channels that
need attention, it selects all of them, every run. A filter that always
returns everything is not a filter, and it hides the case it was meant to
catch.

Six hours with a twelve-hour threshold:

    L                    = min(43,200, 86,400) = 43,200
    guaranteed attempts  = floor(43,200 / 21,600) = 2
    survivable failures  = 1
    guaranteed overlap   > 43,200 - 21,600 = 21,600s (6 hours)
    threshold < TTL      -> the predicate actually discriminates

Two independent chances inside every channel's lifetime, at least six hours of
deliberate overlap on the handover, and a predicate that means something.

    cadence         attempts   survivable failures   guaranteed overlap
    ------------------------------------------------------------------
    24h / 24h thr.     1              0                    0s
    12h / 12h thr.     1              0                    0s
    12h / 24h thr.     2              1                43,200s  (degenerate predicate)
     6h / 12h thr.     2              1                21,600s  <- chosen
     6h /  6h thr.     1              0                    0s

The threshold has to be at least twice the interval, and strictly less than
the TTL. `assert_cadence_is_sound()` enforces exactly that at import.

=============================================================================
SCHEDULING
=============================================================================
    gcloud scheduler jobs create http autofill-channel-renewal \\
        --project cairoai \\
        --schedule "0 */6 * * *" \\
        --uri "https://<region>-cairoai.cloudfunctions.net/api/api/autofill/webhooks/renew" \\
        --http-method POST \\
        --oidc-service-account-email <sa>@cairoai.iam.gserviceaccount.com

The endpoint MUST be authenticated (OIDC above, or a shared secret). An open
renewal endpoint lets anyone burn Drive quota and churn every channel.

Note the CLAUDE.md trap: if this becomes a function in `main.py`, it also has
to appear in `functions.yaml`, which is generated by
`scripts/gen_functions_yaml.py` -- the CLI reads that file instead of running
discovery and silently drops anything missing from it.

=============================================================================
UNVERIFIED
=============================================================================
The arithmetic in this module is tested and the simulation below is exercised
across every creation phase. What has NOT happened: a real channel created
against a real Drive account and observed to survive past its original
expiry. That needs a live OAuth connection. See `providers/VERIFICATION.md`.
"""

from __future__ import annotations

import logging
import math
import time
from typing import Any, Callable, Iterable

from agent_autofill.providers import channel_registry
from agent_autofill.providers.base_provider import WebhookChannel

__all__ = [
    "DRIVE_CHANNEL_MAX_TTL_SECONDS",
    "DRIVE_CHANNEL_DEFAULT_TTL_SECONDS",
    "RENEWAL_INTERVAL_SECONDS",
    "RENEWAL_THRESHOLD_SECONDS",
    "MIN_GUARANTEED_ATTEMPTS",
    "CRON_SCHEDULE",
    "eligible_window_seconds",
    "guaranteed_attempts",
    "guaranteed_overlap_seconds",
    "survivable_consecutive_failures",
    "threshold_is_degenerate",
    "assess_cadence",
    "assert_cadence_is_sound",
    "simulate_renewal",
    "run_renewal_cycle",
]

logger = logging.getLogger("agent_autofill.webhooks")

# Google's limits. Not ours to choose.
DRIVE_CHANNEL_MAX_TTL_SECONDS = 86_400
DRIVE_CHANNEL_DEFAULT_TTL_SECONDS = 3_600

# Ours. See the table above.
RENEWAL_INTERVAL_SECONDS = 6 * 3_600    # 21,600
RENEWAL_THRESHOLD_SECONDS = 12 * 3_600  # 43,200

MIN_GUARANTEED_ATTEMPTS = 2

CRON_SCHEDULE = "0 */6 * * *"


# =============================================================================
# The arithmetic
# =============================================================================


def eligible_window_seconds(ttl: float, threshold: float) -> float:
    """
    Length of the interval during which a channel qualifies for renewal.

    Capped at the TTL because a channel cannot be eligible before it exists --
    this is what makes a threshold larger than the TTL contribute nothing.
    """
    return min(float(threshold), float(ttl))


def guaranteed_attempts(ttl: float, interval: float, threshold: float) -> int:
    """
    Renewal attempts guaranteed inside the eligible window, worst-case phase.

    `floor(L / P)`: ticks are spaced `interval` apart with arbitrary phase, so
    a half-open window of length L contains at least floor(L / P) of them.
    Rounding up here would be assuming the scheduler happens to be aligned
    with the moment a user connected their Drive.
    """
    if interval <= 0:
        raise ValueError("interval must be positive")
    return int(math.floor(eligible_window_seconds(ttl, threshold) / float(interval)))


def guaranteed_overlap_seconds(ttl: float, interval: float, threshold: float) -> float:
    """
    Lower bound on how long the replacement and the old channel coexist.

    Strictly, the overlap is > L - P; this returns L - P (clamped at zero) as
    the safe floor. Overlap is not waste: it is the margin that absorbs clock
    skew between our scheduler and Google's expiry, and it means no change can
    fall into a gap between two channels.
    """
    return max(0.0, eligible_window_seconds(ttl, threshold) - float(interval))


def survivable_consecutive_failures(ttl: float, interval: float, threshold: float) -> int:
    """How many runs in a row may fail before the channel is lost."""
    return max(0, guaranteed_attempts(ttl, interval, threshold) - 1)


def threshold_is_degenerate(ttl: float, threshold: float) -> bool:
    """
    True when "expiring within `threshold`" is true for every live channel.

    At that point the predicate selects everything from the moment of
    creation, which is not a filter and disguises the channels that are
    genuinely close to expiry.
    """
    return float(threshold) >= float(ttl)


def assess_cadence(
    ttl: float = DRIVE_CHANNEL_MAX_TTL_SECONDS,
    interval: float = RENEWAL_INTERVAL_SECONDS,
    threshold: float = RENEWAL_THRESHOLD_SECONDS,
    min_attempts: int = MIN_GUARANTEED_ATTEMPTS,
) -> dict[str, Any]:
    """Full verdict on a proposed schedule. Pure arithmetic, no I/O."""
    attempts = guaranteed_attempts(ttl, interval, threshold)
    overlap = guaranteed_overlap_seconds(ttl, interval, threshold)
    degenerate = threshold_is_degenerate(ttl, threshold)
    sufficient = attempts >= min_attempts and overlap > 0 and not degenerate

    reasons: list[str] = []
    if attempts < min_attempts:
        reasons.append(
            f"only {attempts} guaranteed renewal attempt(s) per channel lifetime; "
            f"{min_attempts} required so a single failed run is survivable"
        )
    if overlap <= 0:
        reasons.append(
            "guaranteed overlap is zero -- the replacement would be created at "
            "the instant of expiry, leaving no margin for scheduler or clock skew"
        )
    if degenerate:
        reasons.append(
            f"threshold ({threshold:.0f}s) >= channel TTL ({ttl:.0f}s), so every "
            "channel qualifies from the moment it is created and the predicate "
            "selects everything"
        )

    return {
        "ttl_seconds": float(ttl),
        "interval_seconds": float(interval),
        "threshold_seconds": float(threshold),
        "eligible_window_seconds": eligible_window_seconds(ttl, threshold),
        "guaranteed_attempts": attempts,
        "survivable_consecutive_failures": survivable_consecutive_failures(
            ttl, interval, threshold
        ),
        "guaranteed_overlap_seconds": overlap,
        "threshold_is_degenerate": degenerate,
        "sufficient": sufficient,
        "reasons": reasons,
    }


def assert_cadence_is_sound(
    ttl: float = DRIVE_CHANNEL_MAX_TTL_SECONDS,
    interval: float = RENEWAL_INTERVAL_SECONDS,
    threshold: float = RENEWAL_THRESHOLD_SECONDS,
) -> dict[str, Any]:
    """Raise if the configured schedule cannot keep a channel alive."""
    verdict = assess_cadence(ttl, interval, threshold)
    if not verdict["sufficient"]:
        raise ValueError(
            "renewal cadence is unsound: " + "; ".join(verdict["reasons"])
        )
    return verdict


# Fails loudly at import if someone edits the constants into a broken schedule.
CADENCE = assert_cadence_is_sound()


# =============================================================================
# Simulation
# =============================================================================


def simulate_renewal(
    created_at: float,
    ttl_seconds: float = DRIVE_CHANNEL_MAX_TTL_SECONDS,
    interval_seconds: float = RENEWAL_INTERVAL_SECONDS,
    threshold_seconds: float = RENEWAL_THRESHOLD_SECONDS,
    cron_epoch: float = 0.0,
    failing_runs: int = 0,
) -> dict[str, Any]:
    """
    Walk a channel's life against a fixed-phase cron and report what happens.

    `cron_epoch` is the wall-clock anchor of the schedule; ticks fall at
    `cron_epoch + k * interval`. `created_at` is deliberately independent of
    it, because a user connects their Drive whenever they like. `failing_runs`
    makes the first N eligible attempts fail, which is how the "survives a
    missed run" property is checked rather than assumed.

    Returns the renewal instant, the overlap it achieved, and whether the
    channel died first.
    """
    expiry = created_at + ttl_seconds
    first_k = math.ceil((created_at - cron_epoch) / interval_seconds)

    ticks: list[float] = []
    eligible: list[float] = []
    renewed_at: float | None = None
    failures_left = int(failing_runs)

    k = first_k
    while True:
        tick = cron_epoch + k * interval_seconds
        if tick >= expiry:
            break
        ticks.append(tick)
        if (expiry - tick) <= threshold_seconds:
            eligible.append(tick)
            if renewed_at is None:
                if failures_left > 0:
                    failures_left -= 1
                else:
                    renewed_at = tick
        k += 1

    return {
        "created_at": created_at,
        "expiry": expiry,
        "ttl_seconds": ttl_seconds,
        "interval_seconds": interval_seconds,
        "threshold_seconds": threshold_seconds,
        "failing_runs": int(failing_runs),
        "ticks_before_expiry": len(ticks),
        "eligible_ticks": len(eligible),
        "first_eligible_at": eligible[0] if eligible else None,
        "renewed_at": renewed_at,
        "renewed_before_expiry": renewed_at is not None,
        "overlap_seconds": (expiry - renewed_at) if renewed_at is not None else 0.0,
    }


# =============================================================================
# The job
# =============================================================================


def run_renewal_cycle(
    provider_factory: Callable[[str], Any] | None = None,
    now: float | None = None,
    threshold_seconds: float = RENEWAL_THRESHOLD_SECONDS,
    providers: Iterable[str] = ("google_drive",),
) -> dict[str, Any]:
    """
    Renew every channel inside the threshold. Safe to run more often than
    scheduled; renewing early only lengthens the overlap.

    One channel's failure never aborts the cycle -- a single company with a
    revoked token would otherwise stop every other company's channel from
    being renewed, which converts one broken connection into an outage.

    Dropbox is not in `providers` by default: its webhook registration lives
    in the App Console and does not expire, so it has nothing to renew. Its
    rows carry `expiration_at = inf` and can never match the query anyway.
    """
    now = time.time() if now is None else now
    if provider_factory is None:
        provider_factory = _default_provider_factory

    report: dict[str, Any] = {
        "ran_at": now,
        "threshold_seconds": threshold_seconds,
        "interval_seconds": RENEWAL_INTERVAL_SECONDS,
        "due": 0,
        "renewed": 0,
        "failed": 0,
        "already_expired": 0,
        "details": [],
    }

    for provider_name in providers:
        due: list[WebhookChannel] = channel_registry.channels_due_for_renewal(
            now=now, threshold_seconds=threshold_seconds, provider=provider_name
        )
        report["due"] += len(due)
        if not due:
            continue

        provider = provider_factory(provider_name)
        for channel in due:
            remaining = channel.seconds_remaining(now)
            entry: dict[str, Any] = {
                "provider": provider_name,
                "channel_id": channel.channel_id,
                "company_id": channel.company_id,
                "seconds_remaining": round(remaining),
            }
            if remaining <= 0:
                report["already_expired"] += 1
                entry["was_expired"] = True

            try:
                new_channel = provider.renew_webhook(channel.channel_id, now=now)
            except Exception as exc:
                report["failed"] += 1
                entry["status"] = "failed"
                entry["error"] = f"{type(exc).__name__}: {exc}"
                logger.error(
                    "channel renewal failed provider=%s channel_id=%s company_id=%s",
                    provider_name,
                    channel.channel_id,
                    channel.company_id,
                    exc_info=True,
                )
            else:
                report["renewed"] += 1
                entry["status"] = "renewed"
                entry["new_channel_id"] = new_channel.channel_id
                entry["new_expiration_at"] = new_channel.expiration_at
                entry["overlap_seconds"] = round(
                    max(0.0, channel.expiration_at - now)
                )
            report["details"].append(entry)

    logger.info(
        "channel renewal cycle complete due=%s renewed=%s failed=%s already_expired=%s",
        report["due"],
        report["renewed"],
        report["failed"],
        report["already_expired"],
    )
    return report


def _default_provider_factory(name: str) -> Any:
    if name == "google_drive":
        from agent_autofill.providers.google_drive_provider import GoogleDriveProvider

        return GoogleDriveProvider()
    if name == "dropbox":
        from agent_autofill.providers.dropbox_provider import DropboxProvider

        return DropboxProvider()
    raise ValueError(f"unknown provider: {name!r}")


def main() -> int:  # pragma: no cover - operational entry point
    """CLI entry point, for a Cloud Scheduler job that shells out."""
    import json

    result = run_renewal_cycle()
    print(json.dumps(result, indent=2, default=str))
    return 1 if result["failed"] else 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
